global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gin-app'
    static_configs:
      - targets: ['app:3030']

  - job_name: 'nginx'
    metrics_path: /nginx_status
    static_configs:
      - targets: ['nginx:9050']
